---
- hosts: all
  become: yes
  vars_files:
  - ./vars.yml

  tasks:

    - name: Install Epel-Release
      yum:
        name: epel-release
        state: latest

    - name: Configure Jenkins Repo
      get_url:
        url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Add Jenkins repo GPG key
      rpm_key:
        state: present
        key: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

    - name: Install Java
      yum:
        name: java-1.8.0-openjdk.x86_64
        state: latest

    - name: Install Python LibSEManage
      yum:
        name: libsemanage-python
        state: latest

    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
   
    - name: Install Nginx
      yum:
        name: nginx 
        state: latest

    - name: SELinux seboolean for HTTPD (Nginx)
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Configure Nginx to host Jenkins
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Enable and Start Firewall
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open Port for Jenkins
      firewalld:
         zone: public
         port: 8080/tcp
         permanent: true
         state: enabled

    - name: Open Port for Nginx
      firewalld:
         zone: public
         service: http
         permanent: true
         state: enabled

    - name: Reload Firewall
      service:
        name: firewalld
        state: reloaded
        enabled: yes