---
- hosts: all
  become: yes
  vars_files:
  - ./vars.yml

  tasks:

    - name: Install Epel-Release
      yum:
        name: epel-release
        state: latest

    - name: Add Kibana Repo GPG key
      rpm_key:
        state: present
        key: http://packages.elastic.co/GPG-KEY-elasticsearch

    - name: Install net-tools
      yum:
        name: net-tools
        state: latest

    - name: Install Python LibSEManage
      yum:
        name: libsemanage-python
        state: latest

    - name: Install Kibana 5.1.1
      yum:
        name: https://artifacts.elastic.co/downloads/kibana/kibana-5.1.1-x86_64.rpm
        state: present

    - name: Configure Kibana
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml

    - name: Start Kibana Service
      service:
        name: kibana
        state: started
        enabled: yes

    - name: Install Nginx
      yum:
        name: nginx 
        state: latest

    - name: SELinux seboolean for HTTPD (Nginx)
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Configure Nginx to host Kibana
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Start Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes
