Vagrant.configure("2") do |config|

  # ***************Elastic Search Server*************

  config.vm.box = "centos/7"
  config.vm.define :elastic do |elastic_config|
  elastic_config.vm.hostname = "elastic.devops.local"
  elastic_config.vm.network "private_network", ip: "192.168.50.50"
  elastic_config.vm.provision "ansible" do |ansible_elastic|
    ansible_elastic.playbook = "elastic.yml"
  elastic_config.vm.provider "virtualbox" do |elastic_v|
    elastic_v.memory = 4096
  end
  end
  end

  # ***************LogStash**************************

  config.vm.box = "centos/7"
  config.vm.define :logstash do |logstash_config|
  logstash_config.vm.hostname = "logstash.devops.local"
  logstash_config.vm.network "private_network", ip: "192.168.50.51"
  logstash_config.vm.provision "ansible" do |ansible_logstash|
    ansible_logstash.playbook = "logstash.yml"
  end
  end

  # ********************Kibana***********************

  config.vm.box = "centos/7"
  config.vm.define :kibana do |kibana_config|
  kibana_config.vm.hostname = "kibana.devops.local"
  kibana_config.vm.network "private_network", ip: "192.168.50.52"
  kibana_config.vm.provision "ansible" do |ansible_kibana|
    ansible_kibana.playbook = "kibana.yml"
  end
  end

end
