Vagrant.configure("2") do |config|

  # ***************Elastic Search Server*************

  config.vm.box = "centos/7"
  config.vm.define :elastic do |elastic_config|
  elastic_config.vm.hostname = "elastic.devops.local"
  elastic_config.vm.network "private_network", ip: "192.168.50.50"
  end

  

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "elastic.yml"
  #end

  # ***************LogStash**************************

  config.vm.box = "centos/7"
  config.vm.define :logstash do |logstash_config|
  logstash_config.vm.hostname = "logstash.devops.local"
  logstash_config.vm.network "private_network", ip: "192.168.50.51"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "logstash.yml"
  #end

  # ********************Kibana***********************

  config.vm.box = "centos/7"
  config.vm.define :kibana do |kibana_config|
  kibana_config.vm.hostname = "kibana.devops.local"
  kibana_config.vm.network "private_network", ip: "192.168.50.52"
  end



  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # config.vm.provision "ansible" do |ansible|
  # ansible.playbook = "kibana.yml"
  #end

end
